[package]
name = "portal"
version = "0.1.0"
authors = ["Kolby ML (Moroz Liebl) <kolbydml@gmail.com>"]
edition = "2021"

[dependencies]
alloy-rlp = "0.3.8"
alloy-primitives = "0.8.0"
ethportal-api = { git = "https://github.com/ethereum/trin", rev = "c416cd9faf933f89b44a517ca7ada144bf2baee9" }
futures = "0.3.25"
hivesim = { git = "https://github.com/ethereum/hive", rev = "5c589295dae3eb896a5cb71ee639ab01add911a5" }
itertools = "0.10.5"
serde_json = "1.0.95"
serde_yaml = "0.9.33"
tokio = { version = "1.14.0", features = ["full"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.16"

